locales:
  # - ca
  # - en

contact:
  email: livinglab@ari.ad
  phone: +376 862 555
  social:
    facebook: https://www.facebook.com/AndorraRecercaInnovacio
    twitter: https://twitter.com/Andorra_RI
    instagram: https://www.instagram.com/andorra_ri
    youtube: https://www.youtube.com/channel/UC_sgrb5DXkWphnjcW1YThzg
    linkedin: https://www.linkedin.com/company/andorra-recerca-i-innovaci%C3%B3/

navigation:
  home: landing
  case_studies: case-studies
  contact: contact

landing:
  cover: images/mountains.jpg

livinglab:
  images:
    side:
      path: https://images.unsplash.com/photo-1609747073474-596e8b94c082
      caption: Photo by IBolat on Unsplash
    thumbnail:
      path: /images/project_whiteboard.jpg
  join:
    url: mailto:livinglab@ari.ad

  keypoints:
    - agility
    - proximity
    - country_scale
    - regulation
    - support

  benefits:
    - exploration
    - co-creation
    - experimentation
    - evaluation

sectors:
  - title: mountain
    cover: https://media.istockphoto.com/photos/quadcopter-flying-on-background-volcanic-peak-aerial-videography-picture-id1287578380?k=20&m=1287578380&s=612x612&w=0&h=5Uc8VUbdnR_BFCov47drwqXZVZ89TRJBviMeRTeawxs=
  - title: sport
    cover: https://media.istockphoto.com/photos/running-on-tracks-picture-id616002088?k=20&m=616002088&s=612x612&w=0&h=32pfx-irqVLziKPPl_oE46oX_6CZeEtMk8TIpa8TKbc=
  - title: sustainability
    cover: https://media.istockphoto.com/photos/scientist-inspecting-plants-picture-id637078430?b=1&k=20&m=637078430&s=170667a&w=0&h=_DNsCqGi_NoddLHxsAzamydL_zRIKppOlRYaS2hS64I=
  - title: education
    cover: https://media.istockphoto.com/photos/in-a-computer-science-class-boy-wearing-virtual-reality-headset-works-picture-id1089737754?k=20&m=1089737754&s=612x612&w=0&h=T49ftz0UZktQOEiTXvfeUQWBqyn8BfQ22fJ2sb5let8=

testimonials:
  cover: https://media.istockphoto.com/photos/young-african-american-girl-playing-game-using-vr-glasses-enjoying-picture-id1201598872?k=20&m=1201598872&s=612x612&w=0&h=gQfqYafj6hJTlqDLO4jEkrupZYm9XWaPuhNgSPHzBHc=

api:
  base: appVfnAvub5J7YzZl
  resources:
    PROJECTS:
      endpoint: projects
      localized:
        - name
        - abstract
      fields:
        - name
        - cover
        - abstract
        - area
      sort:
        order: asc
        id: desc
      where:
        constraints: 1
        active:
          checked: true

    PARTNERS:
      endpoint: partners
      fields:
        - name
        - web
        - logo
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true

    TESTIMONIALS:
      endpoint: testimonials
      localized:
        - testimonial
      fields:
        - name
        - photo
        - company
        - testimonial
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true
