locales:
  - ca
  - en

contact:
  email: livinglab@ari.ad
  phone: +376 862 555
  social:
    Facebook: https://www.facebook.com/AndorraRecercaInnovacio
    Twitter: https://twitter.com/Andorra_RI
    Instagram: https://www.instagram.com/andorra_ri
    Youtube: https://www.youtube.com/channel/UC_sgrb5DXkWphnjcW1YThzg
    Linkedin: https://www.linkedin.com/company/andorra-recerca-i-innovaci%C3%B3/

links:
  ari: https://www.ari.ad
  andorrabiosfera: https://andorrabiosfera.ad/

navigation:
  home: /
  challenges: /#challenges
  case_studies: /#case-studies
  contact: '#contact'

landing:
  cover: images/mountains.jpg

livinglab:
  video:
    # https://www.youtube.com/embed/{id}
    # https://player.vimeo.com/video/{id}
    source:
      en: https://www.youtube.com/embed/sTTH6LT8p2Y
      ca: https://www.youtube.com/embed/MSorJ2hC75M
    cover: /images/team_living_lab.jpg
  images:
    side:
      path: /images/4_helix_en.png
    thumbnail:
      path: https://images.unsplash.com/flagged/photo-1556514767-5c270b96a005?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Z2xhc3MlMjBib2FyZHxlbnwwfHwwfHw%3D&w=1000&q=80
      caption: Photo by Diggity Marketing on Unsplash
      style:
        --brightness: 1.25
        --blending: multiply
  join:
    url: mailto:livinglab@ari.ad

  keypoints:
    - proximity
    - logistics
    - cocreation
    - regulation

  benefits:
    - exploration
    - co-creation
    - experimentation
    - evaluation

sectors:
  - title: mountain
    cover:
      url: https://images.unsplash.com/photo-1515405969538-5642ed9d0cc4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80
      caption: photo by eric Odiin on Unsplash
  - title: sport_health_wellness
    cover:
      url: https://images.unsplash.com/photo-1577344718665-3e7c0c1ecf6b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80
      caption: Photo by Max on Unsplash
      style:
        --brightness: 2
  - title: sustainability
    cover:
      url: https://images.unsplash.com/photo-1531818824911-2514c27dced3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80
      caption: photo by Rainier Ridao on Unsplash
      style:
        --brightness: 1.4
        --contrast: 1.3
  - title: education
    cover:
      url: https://images.unsplash.com/photo-1585980243496-fe29a36bd382?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1898&q=80
      caption: photo by adam winger on Unsplash
      style:
        --brightness: 1.2
        --contrast: 1.1

testimonials:
  cover:
    url: https://images.unsplash.com/photo-1587400520167-0a46c3c98582?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1000&q=80
    caption: photo by Christine Sandu on Unsplash
    style:
      --brightness: 1.5
      --contrast: 1.5

api:
  base: appVfnAvub5J7YzZl
  resources:
    PROJECTS:
      endpoint: projects
      list:
        localized:
          - name
          - abstract
        fields:
          - slug
          - name
          - cover
          - abstract
          - area
        sort:
          order: asc
        where:
          constraints: 1
          active:
            checked: true
      single:
        localized:
          - name
          - description
        fields:
          - name
          - description
          - cover
          - area
          - url
          - documents

    CHALLENGES:
      endpoint: challenges
      list:
        localized:
          - name
        fields:
          - slug
          - name
          - cover
          - date_start
          - date_end
        sort:
          date_start: desc
        where:
          constraints: 1
          active:
            checked: true
      single:
        localized:
          - name
          - description
        fields:
          - name
          - description
          - cover
          - link
          - date_start
          - date_end

    PARTNERS:
      endpoint: partners
      fields:
        - name
        - web
        - logo
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true

    TESTIMONIALS:
      endpoint: testimonials
      localized:
        - testimonial
      fields:
        - name
        - photo
        - company
        - testimonial
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true
