locales:
  - ca
  - en

contact:
  email: livinglab@ari.ad
  phone: +376 862 555
  social:
    Facebook: https://www.facebook.com/AndorraRecercaInnovacio
    Twitter: https://twitter.com/Andorra_RI
    Instagram: https://www.instagram.com/andorra_ri
    Youtube: https://www.youtube.com/channel/UC_sgrb5DXkWphnjcW1YThzg
    Linkedin: https://www.linkedin.com/company/andorra-recerca-i-innovaci%C3%B3/

links:
  ari: https://www.ari.ad
  andorrabiosfera: https://andorrabiosfera.ad/

navigation:
  home: /
  challenges: /#challenges
  case_studies: /#case-studies
  contact: '#contact'

landing:
  cover: images/mountains.jpg

livinglab:
  video:
    # https://www.youtube.com/embed/{id}
    # https://player.vimeo.com/video/{id}
    source:
      en: https://www.youtube.com/embed/sTTH6LT8p2Y
      ca: https://www.youtube.com/embed/MSorJ2hC75M
    cover: /images/team_living_lab.jpg
  images:
    side:
      path: /images/4_helix_en.png
    thumbnail:
      path: /images/project_whiteboard.jpg
      caption: Photo by Kvalifik on Unsplash
  join:
    url: mailto:livinglab@ari.ad

  keypoints:
    - proximity
    - logistics
    - cocreation
    - regulation

  benefits:
    - exploration
    - co-creation
    - experimentation
    - evaluation

sectors:
  - title: mountain
    cover: https://media.istockphoto.com/photos/quadcopter-flying-on-background-volcanic-peak-aerial-videography-picture-id1287578380?k=20&m=1287578380&s=612x612&w=0&h=5Uc8VUbdnR_BFCov47drwqXZVZ89TRJBviMeRTeawxs=
  - title: sport_health_wellness
    cover: https://media.istockphoto.com/photos/running-on-tracks-picture-id616002088?k=20&m=616002088&s=612x612&w=0&h=32pfx-irqVLziKPPl_oE46oX_6CZeEtMk8TIpa8TKbc=
  - title: sustainability
    cover: https://media.istockphoto.com/photos/scientist-inspecting-plants-picture-id637078430?b=1&k=20&m=637078430&s=170667a&w=0&h=_DNsCqGi_NoddLHxsAzamydL_zRIKppOlRYaS2hS64I=
  - title: education
    cover: https://media.istockphoto.com/photos/in-a-computer-science-class-boy-wearing-virtual-reality-headset-works-picture-id1089737754?k=20&m=1089737754&s=612x612&w=0&h=T49ftz0UZktQOEiTXvfeUQWBqyn8BfQ22fJ2sb5let8=

testimonials:
  cover: https://media.istockphoto.com/photos/young-african-american-girl-playing-game-using-vr-glasses-enjoying-picture-id1201598872?k=20&m=1201598872&s=612x612&w=0&h=gQfqYafj6hJTlqDLO4jEkrupZYm9XWaPuhNgSPHzBHc=

api:
  base: appVfnAvub5J7YzZl
  resources:
    PROJECTS:
      endpoint: projects
      list:
        localized:
          - name
          - abstract
        fields:
          - slug
          - name
          - cover
          - abstract
          - area
        sort:
          order: asc
        where:
          constraints: 1
          active:
            checked: true
      single:
        localized:
          - name
          - description
        fields:
          - name
          - description
          - cover
          - area
          - url
          - documents

    CHALLENGES:
      endpoint: challenges
      list:
        localized:
          - name
        fields:
          - slug
          - name
          - cover
          - date_start
          - date_end
        sort:
          date_start: desc
        where:
          constraints: 1
          active:
            checked: true
      single:
        localized:
          - name
          - description
        fields:
          - name
          - description
          - cover
          - link
          - date_start
          - date_end

    PARTNERS:
      endpoint: partners
      fields:
        - name
        - web
        - logo
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true

    TESTIMONIALS:
      endpoint: testimonials
      localized:
        - testimonial
      fields:
        - name
        - photo
        - company
        - testimonial
      sort:
        order: asc
      where:
        constraints: 1
        active:
          checked: true
